[package]
name = "wind"
version = "0.1.0"
authors = ["Hiroki Minagawa <minagawah@tokyo800.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noise = "0.5.1"

[lib]
crate-type = ["cdylib"]
